version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: 'loja'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'user'
    ports:      
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db: